### ISSUE TITLE
SymbolNotFound error

### ISSUE THREAD

**Issue by ymfa** [nerddan/zipline-bitmex#1]
Thank you for making this data bundle. I installed/ingested it following the three steps, but it seems that the symbols XBTUSD and XBTU17 cannot be found. Could you advise on how this bundle should be used, as I'm new to zipline?

I ran a very simple example `zipline run -f test.py --start 2017-08-02 --end 2017-08-04 -o out.pickle -b bitmex` from the command line. The content of `test.py` is the following.

```Python
from zipline.api import order, record, symbol, sid

def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('XBTUSD'), 1)
```

The error is `zipline.errors.SymbolNotFound: Symbol 'XBTUSD' was not found.` I tried other symbols such as XBT and BTC, but it still didn't work.

**Comment by Zhang-Jack** [comment]
I just got the same issue, and is there anybody here could help?

I tried to run the simple command below:
zipline run -f algo_fake.py -b bitmex -s 2017-7-1 -e 2017-7-2 --trading-calendar bitmex --data-frequency minute

and the content of algo_fake.py is the following:

```
from zipline.api import (
    order_target_percent,
    set_benchmark,
    symbol
)
from zipline.data.bundles import register
from zipline_bitmex import bitmex

def initialize(context):
    pass

def handle_data(context, data):
    order_target_percent(symbol('XBTUSD'), 0.5)
```

The logs show below:

(env_zipline) C:\Users\Administrator>zipline run -f algo_fake.py -b bitmex -s 2017-7-1 -e 2017-7-2 --trading-calendar bitmex --data-frequency minute
[2018-07-09 02:47:03.954901] INFO: Loader: Cache at C:\Users\Administrator/.zipline\data\SPY_benchmark.csv does not have data from 1990-01-02 00:00:00+00:00 to 2018-07-09 00:00:00+00:00.

[2018-07-09 02:47:03.954901] INFO: Loader: Downloading benchmark data for 'SPY' from 1989-12-29 00:00:00+00:00 to 2018-07-09 00:00:00+00:00
[2018-07-09 02:47:05.802007] WARNING: Loader: Still don't have expected benchmark data for 'SPY' from 1989-12-29 00:00:00+00:00 to 2018-07-09 00:00:00+00:00 after redownload!
[2018-07-09 02:47:05.855010] INFO: Loader: Cache at C:\Users\Administrator/.zipline\data\treasury_curves.csv does not have data from 1990-01-02 00:00:00+00:00 to 2018-07-09 00:00:00+00:00.

[2018-07-09 02:47:05.855010] INFO: Loader: Downloading treasury data for 'SPY' from 1990-01-02 00:00:00+00:00 to 2018-07-09 00:00:00+00:00
[2018-07-09 02:49:00.137546] WARNING: Loader: Still don't have expected treasury data for 'SPY' from 1990-01-02 00:00:00+00:00 to 2018-07-09 00:00:00+00:00 after redownload!
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\assets\assets.py", line 703, in _lookup_symbol_strict
    share_class_symbol,
KeyError: ('XBTUSD', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\env_zipline\Scripts\zipline-script.py", line 11, in <module>
    load_entry_point('zipline==1.2.0', 'console_scripts', 'zipline')()
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\__main__.py", line 98, in _
    return f(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\__main__.py", line 259, in run
    environ=os.environ,
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\utils\run_algo.py", line 208, in _run
    overwrite_sim_params=False,
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\algorithm.py", line 730, in run
    for perf in self.get_generator():
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\gens\tradesimulation.py", line 206, in transform
    for capital_change_packet in every_bar(dt):
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\gens\tradesimulation.py", line 134, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\utils\events.py", line 216, in handle_data
    dt,
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\utils\events.py", line 235, in handle_data
    self.callback(context, data)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\algorithm.py", line 465, in handle_data
    self._handle_data(self, data)
  File "algo_fake.py", line 15, in handle_data
    order_target_percent(symbol('XBTUSD'), 0.5)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\utils\api_support.py", line 56, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\algorithm.py", line 1189, in symbol
    """Lookup an Equity by its ticker symbol.
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\algorithm.py", line 1219, in symbol
    as_of_date=_lookup_date,
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\assets\assets.py", line 838, in lookup_symbol
    return self._lookup_symbol_strict(symbol, as_of_date)
  File "C:\ProgramData\Miniconda3\envs\env_zipline\lib\site-packages\zipline\assets\assets.py", line 708, in _lookup_symbol_strict
    raise SymbolNotFound(symbol=symbol)
zipline.errors.SymbolNotFound: Symbol 'XBTUSD' was not found.

**Comment by dancju** [comment]
@ymfa @Zhang-Jack 
Did you register bitmex according the `README.me`?

**Comment by ymfa** [comment]
Yes, I've verified that the file `~/.zipline/extension.py` on my computer is identical to what is described in Step 2.

**Comment by Zhang-Jack** [comment]
@nerdDan Hi, 
I fixed this issue by 
1.adding a new 24-7 calendar in zipline bitmex directory 
2.changed the 'futures' to 'symbol'
it seems that now zipline does not support the futures trading in Bitmex yet.

**Comment by dancju** [comment]
@Zhang-Jack That is great. Would you mind issuing a PR?

**Comment by Zhang-Jack** [comment]
@nerdDan Hi Dan, 
Thank you, do you mean that I submit an issue to the zipline team and tell them to support the futures function?

**Comment by dancju** [comment]
@Zhang-Jack I mean you could launch a pull request to this repo.

**Comment by brigittenico** [comment]
> @nerdDan Hi,
> I fixed this issue by
> 1.adding a new 24-7 calendar in zipline bitmex directory
> 2.changed the 'futures' to 'symbol'
> it seems that now zipline does not support the futures trading in Bitmex yet.

Hello @Zhang-Jack  ! I stumble upon the same error, and did not manage to fix it. The 24/7 calendar is already set in zipline_bitmex, and the only mention of the string 'futures' is line 101 of zipline_bitmex/bitmex.py - I tried to change it for 'symbol' and reingest the data before running zipline without success.

**Comment by nerdDan** [comment]
@brigittenico would you mind create a pull request?

**Comment by SirbitoX** [comment]
Hello @nerdDan I stuck with same problem. I've changed line 101 ```futures``` to ```symbol``` but got same error.
@Zhang-Jack would you please describe more how you fixed this issue?

**Comment by dancju** [comment]
I have found the reasons for this `SymbolNotFound` issue.

First, I missed a return statement [1] for the `asset_db_writer`, thus Zipline can't find the asset metadata which includes the symbol.

https://github.com/nerdDan/zipline-bitmex/blob/a970e14125c0a343b45a0f5054074df76714eb1f/zipline_bitmex/bitmex_bundle.py#L60

Second, you are supposed to use `future_symbol('XBTUSD')` instead of `symbol('XBTUSD')` since `symbols` is for equities and `future_symbol` is for futures.

Unfortunately, although these two steps would fix this `SymbolNotFound` issue, there are more to be fixed before we can run an algorithm. I'll close this issue and declare this repo unusable in the README file.

@ymfa @Zhang-Jack Thank you for reporting this!
